language: node_js
node_js:
  - 4
  - 5
  - 6
os:
  - linux
  - centos
  - macosx
  - windows
env:
  - NODE_ENV=nightwatch
before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.0.4.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-3.0.4/bin/mongod --dbpath /tmp/data  &
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - npm i -g nsp
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - 'selenium-standalone start 2>&1 &'
  - sleep 3
script:
  - npm test
after_script:
  - nsp check
notifications:
  slack: meanstackjs:YtrF35Q7mPqPW5y6NHyDNvkh
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/2f8affb0a488ea5f5b7c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
sudo: false

